### ISSUE TITLE
Can't build on Ubuntu 18.04

### ISSUE THREAD

**Issue by photoniker** [itom-project/issuesTest#69]
Trying to build itom on Ubuntu 18.04, getting error:

`../itom/sources/itom/DataObject/dataobj.cpp:3113: error: expected primary-expression before ‘>’ token
   _Tp* pt = (*((cv::Mat_<_Tp> *)(*dstMat))).ptr<_Tp>(y);`
